CONTIKI_PROJECT = brass-collect-app
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV4 = 0
CONTIKI_WITH_IPV6 = 0

APPS += brass
PROJECT_SOURCEFILES += app.c
#PROJECT_SOURCEFILES += main.c

#all: main

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
